In [1]:
import numpy as np

import pandas as pd
import math as m

In [4]:
# seed for reproducibility 

np.random.seed(42)
my_data = np.random.randint(0,101,(4,3))

In [5]:
my_data

array([[51, 92, 14],
       [71, 60, 20],
       [82, 86, 74],
       [74, 87, 99]], dtype=int32)

In [6]:
my_index = ['IND','USA','RSS','CHN']
my_columns = ['population_Million','GDP_Million','Government_employee_%']

df = pd.DataFrame(data = my_data, index= my_index, columns= my_columns)
df

     population_Million  GDP_Million  Government_employee_%
IND                  51           92                     14
USA                  71           60                     20
RSS                  82           86                     74
CHN                  74           87                     99

In [7]:
type(df)

pandas.DataFrame

In [13]:
df.head(2)

     population_Million  GDP_Million  Government_employee_%
IND                  51           92                     14
USA                  71           60                     20

In [12]:
df.tail(1)

     population_Million  GDP_Million  Government_employee_%
CHN                  74           87                     99

# Reading Data in Pandas

In [ ]:
df = pd.read_csv("D:\\CUDA_ENV\\Bleep_B1\\2_Data_Handling_Tools\\Pandas\\Data\\tips.csv")   # to read csv file

In [18]:
df

     total_bill   tip     sex smoker   day    time  size  price_per_person
0         16.99  1.01  Female     No   Sun  Dinner     2              8.49
1         10.34  1.66    Male     No   Sun  Dinner     3              3.45
2         21.01  3.50    Male     No   Sun  Dinner     3              7.00
3         23.68  3.31    Male     No   Sun  Dinner     2             11.84
4         24.59  3.61  Female     No   Sun  Dinner     4              6.15
..          ...   ...     ...    ...   ...     ...   ...               ...
239       29.03  5.92    Male     No   Sat  Dinner     3              9.68
240       27.18  2.00  Female    Yes   Sat  Dinner     2             13.59
241       22.67  2.00    Male    Yes   Sat  Dinner     2             11.34
242       17.82  1.75    Male     No   Sat  Dinner     2              8.91
243       18.78  3.00  Female     No  Thur  Dinner     2              9.39

[244 rows x 8 columns]

In [21]:
df_excel = pd.read_excel("D:\\CUDA_ENV\\Bleep_B1\\2_Data_Handling_Tools\\Pandas\\Data\\example.xlsx")

In [22]:
# ! pip install openpyxl

In [23]:
df_excel

    a   b   c   d
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

In [24]:
# reading data from rest api 

TITANIC_DATASET = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"

import pandas as pd

titanic_df = pd.read_csv(TITANIC_DATASET)
titanic_df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [25]:
titanic_df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='str')

In [26]:
CALIFORNIA_HOUSING = "https://raw.githubusercontent.com/ageron/handson-ml2/master/datasets/housing/housing.csv"

df = pd.read_csv(CALIFORNIA_HOUSING)
print(df)
print("features in df:", df.columns)
print("Length of the df", len(df))

       longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -122.23     37.88                41.0        880.0           129.0
1        -122.22     37.86                21.0       7099.0          1106.0
2        -122.24     37.85                52.0       1467.0           190.0
3        -122.25     37.85                52.0       1274.0           235.0
4        -122.25     37.85                52.0       1627.0           280.0
...          ...       ...                 ...          ...             ...
20635    -121.09     39.48                25.0       1665.0           374.0
20636    -121.21     39.49                18.0        697.0           150.0
20637    -121.22     39.43                17.0       2254.0           485.0
20638    -121.32     39.43                18.0       1860.0           409.0
20639    -121.24     39.37                16.0       2785.0           616.0

       population  households  median_income  median_house_value  \
0           322.0       126.0         8.3252            452600.0
1          2401.0      1138.0         8.3014            358500.0
2           496.0       177.0         7.2574            352100.0
3           558.0       219.0         5.6431            341300.0
4           565.0       259.0         3.8462            342200.0
...           ...         ...            ...                 ...
20635       845.0       330.0         1.5603             78100.0
20636       356.0       114.0         2.5568             77100.0
20637      1007.0       433.0         1.7000             92300.0
20638       741.0       349.0         1.8672             84700.0
20639      1387.0       530.0         2.3886             89400.0

      ocean_proximity
0            NEAR BAY
1            NEAR BAY
2            NEAR BAY
3            NEAR BAY
4            NEAR BAY
...               ...
20635          INLAND
20636          INLAND
20637          INLAND
20638          INLAND
20639          INLAND

[20640 rows x 10 columns]
features in df: Index(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income',
       'median_house_value', 'ocean_proximity'],
      dtype='str')
Length of the df 20640